site_name: Sathish Kumar's Scaler Course Site
site_description: This is a site for Scalar Course
site_author: Sathish Kumar
site_url: https://sathishkumar-website.github.io/Scaler-Course/
docs_dir: docs


theme:
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
  #  - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  # - toc.follow
    - toc.integrate
  palette:
    primary: custom
    extra_css:
      - stylesheets/extra.css
  toggle:
    icon: material/brightness-4
    name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Module1 - Data Analytics and Visualization: M1_DAV/dav-readme.md
  - CheatSheets: CheatSheets/cheetsheet.md
  - Datasets: datasets/dataset.md
  - MyDesign: MyDesign/designs-readme.md
  - Projects: Projects/projects-readme.md
  - Python: Python/python-readme.md
  - Tableau: Tableau/tableau-readme.md

